### ISSUE TITLE
Track WF2-related issues in ncats/translator-workflows repo

### ISSUE THREAD

**Issue by jaeddy** [jaeddy/pyreasoner#1]
(skipping CWL-related items for now, as that work might be better suited for a separate repo)

- [ ] [Replace MyGene API with BioThings client in WF2
](https://github.com/ncats/translator-workflows/issues/76)
- [ ] [review WF2 module parameters and parameter exposure through API](https://github.com/ncats/translator-workflows/issues/71)
- [ ] [Create new WF2 module to compute summary report (eg average ranks) for multiple outputs from WF2 standalone script run with input variation](https://github.com/ncats/translator-workflows/issues/68)
- [ ] [Use WF2 standalone script and generate output using variations on input (diseases, gene sets)](https://github.com/ncats/translator-workflows/issues/67)
- [ ] [Convert WF2 nb (batch disease version) to a standalone, monolithic python script](https://github.com/ncats/translator-workflows/issues/65)
